<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'XelaxHTMLPurifier\Module'                       => __DIR__ . '/Module.php',
  'XelaxHTMLPurifier\Filter\HTMLPurifier'          => __DIR__ . '/src/XelaxHTMLPurifier/Filter/HTMLPurifier.php',
);
